server:
  port: 7001
  servlet:
    context-path: /coupon-template

spring:
  application:
    name: coupon-template
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  cloud:
    nacos:
      discovery:
        server-addr: 121.4.35.23:8848 #Nacos地址
  datasource:
    # 数据源
    url: jdbc:mysql://121.4.35.23:3306/coupon?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Admin123!
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 121.4.35.23
    port: 6379
    # password:
    # 连接超时时间
    timeout: 10000

# ------------------------------------------------------------------------------------------------------

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: coupon-template
    groupId: org.example
    artifactId: coupon-template
    version: 1.0-SNAPSHOT

# ------------------------------------------------------------------------------------------------------

logging:
  level:
    org.example.myCoupon: debug
