server:
  port: 7003
  servlet:
    context-path: /coupon-settlement

spring:
  application:
    name: coupon-settlement
  cloud:
    nacos:
      discovery:
        server-addr: 121.4.35.23:8848 #Nacos地址

logging:
  level:
    org.example.myCoupon: debug
